[2025-04-21T16:40:18.240+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-21T16:40:18.248+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl.load_to_postgres manual__2025-04-21T07:00:36.233762+00:00 [queued]>
[2025-04-21T16:40:18.251+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl.load_to_postgres manual__2025-04-21T07:00:36.233762+00:00 [queued]>
[2025-04-21T16:40:18.251+0800] {taskinstance.py:2867} INFO - Starting attempt 7 of 7
[2025-04-21T16:40:18.256+0800] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-04-21 07:00:36.233762+00:00
[2025-04-21T16:40:18.259+0800] {standard_task_runner.py:72} INFO - Started process 20334 to run task
[2025-04-21T16:40:18.263+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_etl', 'load_to_postgres', 'manual__2025-04-21T07:00:36.233762+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/var/folders/mz/6xjq0zld5fj5_cth7lsfpxlr0000gp/T/tmpwjx222ym']
[2025-04-21T16:40:18.264+0800] {standard_task_runner.py:105} INFO - Job 34: Subtask load_to_postgres
[2025-04-21T16:40:18.286+0800] {task_command.py:467} INFO - Running <TaskInstance: weather_etl.load_to_postgres manual__2025-04-21T07:00:36.233762+00:00 [running]> on host luiss-mbp.realtek
[2025-04-21T16:40:18.311+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='weather_etl' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-21T07:00:36.233762+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-21T07:00:36.233762+00:00'
[2025-04-21T16:40:18.311+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-21T16:40:18.312+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-21T16:40:18.312+0800] {logging_mixin.py:190} INFO - Current task name:load_to_postgres state:running start_date:2025-04-21 08:40:18.248246+00:00
[2025-04-21T16:40:18.312+0800] {logging_mixin.py:190} INFO - Dag name:weather_etl and current dag run status:running
[2025-04-21T16:40:18.312+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-21T16:40:18.312+0800] {weather_etl_dag.py:90} INFO - Starting the load_to_postgres function.
[2025-04-21T16:40:18.323+0800] {weather_etl_dag.py:120} ERROR - PostgreSQL error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  role "airflow_user" does not exist

[2025-04-21T16:40:18.324+0800] {python.py:240} INFO - Done. Returned value was: None
[2025-04-21T16:40:18.326+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-21T16:40:18.326+0800] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_etl, task_id=load_to_postgres, run_id=manual__2025-04-21T07:00:36.233762+00:00, execution_date=20250421T070036, start_date=20250421T084018, end_date=20250421T084018
[2025-04-21T16:40:18.333+0800] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-21T16:40:18.333+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-21T16:40:18.333+0800] {logging_mixin.py:190} INFO - Dag name:weather_etl queued_at:2025-04-21 08:40:16.397908+00:00
[2025-04-21T16:40:18.333+0800] {logging_mixin.py:190} INFO - Task hostname:luiss-mbp.realtek operator:PythonOperator
[2025-04-21T16:40:18.357+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-21T16:40:18.363+0800] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-21T16:40:18.364+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
