[2025-04-21T13:42:28.055+0800] {processor.py:186} INFO - Started process (PID=1403) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T13:42:28.057+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T13:42:28.058+0800] {logging_mixin.py:190} INFO - [2025-04-21T13:42:28.058+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T13:42:28.080+0800] {logging_mixin.py:190} INFO - [2025-04-21T13:42:28.076+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T13:42:28.080+0800] {logging_mixin.py:190} INFO - [2025-04-21T13:42:28.080+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T13:42:28.080+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T13:42:28.133+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2025-04-21T13:44:37.098+0800] {processor.py:186} INFO - Started process (PID=1648) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T13:44:37.102+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T13:44:37.103+0800] {logging_mixin.py:190} INFO - [2025-04-21T13:44:37.103+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T13:44:37.127+0800] {logging_mixin.py:190} INFO - [2025-04-21T13:44:37.123+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T13:44:37.127+0800] {logging_mixin.py:190} INFO - [2025-04-21T13:44:37.127+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T13:44:37.127+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T13:44:37.182+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.085 seconds
[2025-04-21T13:47:51.282+0800] {processor.py:186} INFO - Started process (PID=2057) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T13:47:51.285+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T13:47:51.286+0800] {logging_mixin.py:190} INFO - [2025-04-21T13:47:51.286+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T13:47:51.308+0800] {logging_mixin.py:190} INFO - [2025-04-21T13:47:51.305+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T13:47:51.309+0800] {logging_mixin.py:190} INFO - [2025-04-21T13:47:51.309+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T13:47:51.309+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T13:47:51.360+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2025-04-21T13:50:59.779+0800] {processor.py:186} INFO - Started process (PID=2543) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T13:50:59.782+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T13:50:59.783+0800] {logging_mixin.py:190} INFO - [2025-04-21T13:50:59.783+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T13:50:59.806+0800] {logging_mixin.py:190} INFO - [2025-04-21T13:50:59.802+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T13:50:59.806+0800] {logging_mixin.py:190} INFO - [2025-04-21T13:50:59.806+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T13:50:59.806+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T13:50:59.859+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.082 seconds
[2025-04-21T13:54:08.292+0800] {processor.py:186} INFO - Started process (PID=2955) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T13:54:08.295+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T13:54:08.295+0800] {logging_mixin.py:190} INFO - [2025-04-21T13:54:08.295+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T13:54:08.319+0800] {logging_mixin.py:190} INFO - [2025-04-21T13:54:08.315+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T13:54:08.319+0800] {logging_mixin.py:190} INFO - [2025-04-21T13:54:08.319+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T13:54:08.319+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T13:54:08.372+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.082 seconds
[2025-04-21T13:57:19.484+0800] {processor.py:186} INFO - Started process (PID=3618) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T13:57:19.487+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T13:57:19.488+0800] {logging_mixin.py:190} INFO - [2025-04-21T13:57:19.488+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T13:57:19.511+0800] {logging_mixin.py:190} INFO - [2025-04-21T13:57:19.508+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T13:57:19.512+0800] {logging_mixin.py:190} INFO - [2025-04-21T13:57:19.511+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T13:57:19.512+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T13:57:19.563+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2025-04-21T14:00:37.236+0800] {processor.py:186} INFO - Started process (PID=3907) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:00:37.240+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:00:37.241+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:00:37.241+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:00:37.265+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:00:37.262+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:00:37.265+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:00:37.265+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:00:37.266+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:00:37.319+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2025-04-21T14:06:24.177+0800] {processor.py:186} INFO - Started process (PID=4752) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:06:24.181+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:06:24.181+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:06:24.181+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:06:24.202+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:06:24.199+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:06:24.203+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:06:24.202+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:06:24.203+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:06:24.253+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.078 seconds
[2025-04-21T14:10:39.627+0800] {processor.py:186} INFO - Started process (PID=5304) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:10:39.630+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:10:39.630+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:10:39.630+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:10:39.652+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:10:39.648+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:10:39.652+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:10:39.652+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:10:39.653+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:10:39.710+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.085 seconds
[2025-04-21T14:16:29.658+0800] {processor.py:186} INFO - Started process (PID=5842) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:16:29.662+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:16:29.663+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:16:29.662+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:16:29.685+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:16:29.681+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:16:29.685+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:16:29.685+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:16:29.685+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:16:29.737+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2025-04-21T14:18:41.099+0800] {processor.py:186} INFO - Started process (PID=6022) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:18:41.102+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:18:41.103+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:18:41.103+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:18:41.126+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:18:41.122+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:18:41.126+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:18:41.126+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:18:41.126+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:18:41.178+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2025-04-21T14:21:05.478+0800] {processor.py:186} INFO - Started process (PID=6312) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:21:05.481+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:21:05.482+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:21:05.482+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:21:05.504+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:21:05.501+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:21:05.505+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:21:05.505+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:21:05.505+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:21:05.556+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2025-04-21T14:22:51.034+0800] {processor.py:186} INFO - Started process (PID=6536) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:22:51.037+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:22:51.038+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:22:51.038+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:22:51.059+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:22:51.055+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:22:51.059+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:22:51.059+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:22:51.059+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:22:51.112+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.079 seconds
[2025-04-21T14:24:31.730+0800] {processor.py:186} INFO - Started process (PID=6761) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:24:31.734+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:24:31.735+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:24:31.735+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:24:31.757+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:24:31.753+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:24:31.757+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:24:31.757+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:24:31.757+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:24:31.809+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2025-04-21T14:26:24.579+0800] {processor.py:186} INFO - Started process (PID=7061) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:26:24.583+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:26:24.584+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:26:24.584+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:26:24.608+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:26:24.604+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:26:24.609+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:26:24.608+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:26:24.609+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:26:24.661+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2025-04-21T14:28:14.344+0800] {processor.py:186} INFO - Started process (PID=7423) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:28:14.348+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:28:14.348+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:28:14.348+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:28:14.369+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:28:14.366+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:28:14.369+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:28:14.369+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:28:14.369+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:28:14.420+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.077 seconds
[2025-04-21T14:29:51.719+0800] {processor.py:186} INFO - Started process (PID=7619) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:29:51.722+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:29:51.723+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:29:51.723+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:29:51.747+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:29:51.743+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:29:51.747+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:29:51.747+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:29:51.747+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:29:51.799+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.082 seconds
[2025-04-21T14:31:33.822+0800] {processor.py:186} INFO - Started process (PID=7847) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:31:33.825+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:31:33.826+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:31:33.826+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:31:33.851+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:31:33.847+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:31:33.851+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:31:33.851+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:31:33.851+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:31:33.905+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.085 seconds
[2025-04-21T14:33:18.651+0800] {processor.py:186} INFO - Started process (PID=8094) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:33:18.654+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:33:18.655+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:33:18.655+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:33:18.678+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:33:18.674+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:33:18.678+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:33:18.678+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:33:18.678+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:33:18.734+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2025-04-21T14:35:03.508+0800] {processor.py:186} INFO - Started process (PID=8316) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:35:03.512+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:35:03.512+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:35:03.512+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:35:03.537+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:35:03.533+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:35:03.537+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:35:03.537+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:35:03.537+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:35:03.588+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.082 seconds
[2025-04-21T14:36:52.625+0800] {processor.py:186} INFO - Started process (PID=8548) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:36:52.629+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:36:52.630+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:36:52.629+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:36:52.655+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:36:52.651+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:36:52.656+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:36:52.656+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:36:52.656+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:36:52.710+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.087 seconds
[2025-04-21T14:38:35.284+0800] {processor.py:186} INFO - Started process (PID=8820) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:38:35.287+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:38:35.288+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:38:35.288+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:38:35.313+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:38:35.309+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:38:35.313+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:38:35.313+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:38:35.314+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:38:35.367+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.085 seconds
[2025-04-21T14:40:19.698+0800] {processor.py:186} INFO - Started process (PID=9052) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:40:19.702+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:40:19.703+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:40:19.702+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:40:19.726+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:40:19.722+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:40:19.726+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:40:19.726+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:40:19.726+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:40:19.777+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2025-04-21T14:42:08.842+0800] {processor.py:186} INFO - Started process (PID=9308) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:42:08.846+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:42:08.847+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:42:08.847+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:42:08.871+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:42:08.867+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:42:08.871+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:42:08.871+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:42:08.871+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:42:08.924+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2025-04-21T14:59:25.796+0800] {processor.py:186} INFO - Started process (PID=10984) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:59:25.797+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T14:59:25.798+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:59:25.798+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:59:25.813+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:59:25.810+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T14:59:25.813+0800] {logging_mixin.py:190} INFO - [2025-04-21T14:59:25.813+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T14:59:25.813+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T14:59:25.849+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.055 seconds
[2025-04-21T15:01:02.327+0800] {processor.py:186} INFO - Started process (PID=11222) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:01:02.329+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:01:02.329+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:01:02.329+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:01:02.345+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:01:02.342+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:01:02.345+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:01:02.345+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:01:02.345+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:01:02.381+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.055 seconds
[2025-04-21T15:02:04.232+0800] {processor.py:186} INFO - Started process (PID=11401) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:02:04.235+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:02:04.235+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:02:04.235+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:02:04.253+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:02:04.250+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:02:04.253+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:02:04.253+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:02:04.253+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:02:04.291+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2025-04-21T15:03:06.503+0800] {processor.py:186} INFO - Started process (PID=11549) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:03:06.506+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:03:06.506+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:03:06.506+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:03:06.525+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:03:06.522+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:03:06.525+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:03:06.525+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:03:06.525+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:03:06.566+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2025-04-21T15:04:11.526+0800] {processor.py:186} INFO - Started process (PID=11749) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:04:11.529+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:04:11.529+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:04:11.529+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:04:11.545+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:04:11.543+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:04:11.545+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:04:11.545+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:04:11.545+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:04:11.582+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2025-04-21T15:05:11.666+0800] {processor.py:186} INFO - Started process (PID=11914) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:05:11.668+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:05:11.668+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:05:11.668+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:05:11.685+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:05:11.682+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:05:11.685+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:05:11.685+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:05:11.685+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:05:11.723+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2025-04-21T15:06:13.101+0800] {processor.py:186} INFO - Started process (PID=12092) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:06:13.103+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:06:13.104+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:06:13.104+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:06:13.120+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:06:13.117+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:06:13.120+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:06:13.120+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:06:13.120+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:06:13.157+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2025-04-21T15:08:25.633+0800] {processor.py:186} INFO - Started process (PID=12387) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:08:25.636+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:08:25.636+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:08:25.636+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:08:25.654+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:08:25.651+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:08:25.655+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:08:25.654+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:08:25.655+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:08:25.693+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2025-04-21T15:10:23.851+0800] {processor.py:186} INFO - Started process (PID=12672) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:10:23.853+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:10:23.853+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:10:23.853+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:10:23.871+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:10:23.868+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:10:23.871+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:10:23.871+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:10:23.871+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:10:23.910+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2025-04-21T15:11:26.088+0800] {processor.py:186} INFO - Started process (PID=12866) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:11:26.090+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:11:26.091+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:11:26.091+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:11:26.107+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:11:26.104+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:11:26.107+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:11:26.107+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:11:26.107+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:11:26.144+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2025-04-21T15:12:30.642+0800] {processor.py:186} INFO - Started process (PID=13087) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:12:30.644+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:12:30.644+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:12:30.644+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:12:30.660+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:12:30.657+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:12:30.660+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:12:30.660+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:12:30.660+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:12:30.696+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2025-04-21T15:13:36.703+0800] {processor.py:186} INFO - Started process (PID=13266) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:13:36.706+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:13:36.707+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:13:36.706+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:13:36.725+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:13:36.722+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:13:36.725+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:13:36.725+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:13:36.725+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:13:36.763+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2025-04-21T15:14:42.288+0800] {processor.py:186} INFO - Started process (PID=13436) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:14:42.290+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:14:42.291+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:14:42.291+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:14:42.306+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:14:42.304+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:14:42.306+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:14:42.306+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:14:42.307+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:14:42.342+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2025-04-21T15:16:01.543+0800] {processor.py:186} INFO - Started process (PID=13622) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:16:01.545+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:16:01.546+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:16:01.546+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:16:01.562+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:16:01.559+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:16:01.562+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:16:01.562+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:16:01.562+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:16:01.599+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2025-04-21T15:18:53.711+0800] {processor.py:186} INFO - Started process (PID=13919) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:18:53.713+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:18:53.713+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:18:53.713+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:18:53.728+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:18:53.726+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:18:53.728+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:18:53.728+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:18:53.728+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:18:53.764+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.055 seconds
[2025-04-21T15:21:40.715+0800] {processor.py:186} INFO - Started process (PID=14250) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:21:40.717+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:21:40.717+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:21:40.717+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:21:40.736+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:21:40.733+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:21:40.736+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:21:40.736+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:21:40.736+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:21:40.775+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2025-04-21T15:23:34.199+0800] {processor.py:186} INFO - Started process (PID=14518) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:23:34.201+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:23:34.202+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:23:34.202+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:23:34.219+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:23:34.216+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:23:34.219+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:23:34.219+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:23:34.219+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:23:34.259+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2025-04-21T15:24:45.611+0800] {processor.py:186} INFO - Started process (PID=14687) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:24:45.614+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:24:45.614+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:24:45.614+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:24:45.632+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:24:45.629+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:24:45.632+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:24:45.632+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:24:45.632+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:24:45.673+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2025-04-21T15:25:53.445+0800] {processor.py:186} INFO - Started process (PID=14839) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:25:53.447+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:25:53.448+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:25:53.448+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:25:53.465+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:25:53.462+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:25:53.465+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:25:53.465+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:25:53.465+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:25:53.502+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2025-04-21T15:27:15.613+0800] {processor.py:186} INFO - Started process (PID=15042) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:27:15.615+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:27:15.616+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:27:15.616+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:27:15.634+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:27:15.631+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:27:15.634+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:27:15.634+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:27:15.634+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:27:15.675+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2025-04-21T15:28:18.741+0800] {processor.py:186} INFO - Started process (PID=15196) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:28:18.743+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:28:18.744+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:28:18.744+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:28:18.762+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:28:18.759+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:28:18.762+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:28:18.762+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:28:18.762+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:28:18.800+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2025-04-21T15:29:23.321+0800] {processor.py:186} INFO - Started process (PID=15338) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:29:23.323+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:29:23.323+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:29:23.323+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:29:23.343+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:29:23.339+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:29:23.343+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:29:23.343+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:29:23.343+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:29:23.382+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2025-04-21T15:43:16.214+0800] {processor.py:186} INFO - Started process (PID=16033) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:43:16.217+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:43:16.217+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:43:16.217+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:43:16.234+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:43:16.231+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:43:16.234+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:43:16.234+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:43:16.234+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:43:16.275+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2025-04-21T15:44:19.806+0800] {processor.py:186} INFO - Started process (PID=16164) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:44:19.809+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:44:19.809+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:44:19.809+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:44:19.825+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:44:19.822+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:44:19.825+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:44:19.825+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:44:19.825+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:44:19.861+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2025-04-21T15:45:22.968+0800] {processor.py:186} INFO - Started process (PID=16287) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:45:22.971+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:45:22.972+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:45:22.972+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:45:22.988+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:45:22.986+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:45:22.989+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:45:22.989+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:45:22.989+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:45:23.025+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2025-04-21T15:46:29.003+0800] {processor.py:186} INFO - Started process (PID=16457) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:46:29.006+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:46:29.006+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:46:29.006+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:46:29.022+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:46:29.019+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:46:29.022+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:46:29.022+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:46:29.022+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:46:29.058+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2025-04-21T15:47:39.413+0800] {processor.py:186} INFO - Started process (PID=16622) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:47:39.416+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:47:39.417+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:47:39.416+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:47:39.433+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:47:39.430+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:47:39.433+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:47:39.433+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:47:39.433+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:47:39.470+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2025-04-21T15:48:41.734+0800] {processor.py:186} INFO - Started process (PID=16744) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:48:41.736+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:48:41.737+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:48:41.737+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:48:41.754+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:48:41.751+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:48:41.754+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:48:41.754+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:48:41.755+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:48:41.795+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2025-04-21T15:49:42.086+0800] {processor.py:186} INFO - Started process (PID=16871) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:49:42.089+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T15:49:42.089+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:49:42.089+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:49:42.108+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:49:42.104+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T15:49:42.108+0800] {logging_mixin.py:190} INFO - [2025-04-21T15:49:42.108+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T15:49:42.108+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T15:49:42.148+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2025-04-21T16:19:29.455+0800] {processor.py:186} INFO - Started process (PID=17511) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:19:29.458+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:19:29.458+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:19:29.458+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:19:29.475+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:19:29.472+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:19:29.475+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:19:29.475+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:19:29.475+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:19:29.515+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2025-04-21T16:20:39.184+0800] {processor.py:186} INFO - Started process (PID=17669) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:20:39.186+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:20:39.187+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:20:39.187+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:20:39.206+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:20:39.202+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:20:39.206+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:20:39.206+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:20:39.206+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:20:39.248+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2025-04-21T16:21:43.313+0800] {processor.py:186} INFO - Started process (PID=17817) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:21:43.315+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:21:43.316+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:21:43.316+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:21:43.334+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:21:43.331+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:21:43.334+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:21:43.334+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:21:43.334+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:21:43.373+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2025-04-21T16:22:52.387+0800] {processor.py:186} INFO - Started process (PID=17983) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:22:52.389+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:22:52.390+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:22:52.390+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:22:52.406+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:22:52.403+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:22:52.406+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:22:52.406+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:22:52.406+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:22:52.443+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2025-04-21T16:23:53.738+0800] {processor.py:186} INFO - Started process (PID=18126) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:23:53.740+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:23:53.741+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:23:53.740+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:23:53.758+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:23:53.755+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:23:53.759+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:23:53.759+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:23:53.759+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:23:53.799+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2025-04-21T16:24:59.758+0800] {processor.py:186} INFO - Started process (PID=18295) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:24:59.761+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:24:59.761+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:24:59.761+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:24:59.778+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:24:59.775+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:24:59.779+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:24:59.778+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:24:59.779+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:24:59.819+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2025-04-21T16:26:02.979+0800] {processor.py:186} INFO - Started process (PID=18431) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:26:02.983+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:26:02.984+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:26:02.984+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:26:02.999+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:26:02.997+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:26:03.000+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:26:03.000+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:26:03.000+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:26:03.036+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2025-04-21T16:27:07.711+0800] {processor.py:186} INFO - Started process (PID=18569) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:27:07.714+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:27:07.714+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:27:07.714+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:27:07.731+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:27:07.728+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:27:07.731+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:27:07.731+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:27:07.731+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:27:07.768+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2025-04-21T16:29:01.490+0800] {processor.py:186} INFO - Started process (PID=19022) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:29:01.493+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:29:01.493+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:29:01.493+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:29:01.512+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:29:01.508+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:29:01.512+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:29:01.512+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:29:01.512+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:29:01.553+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2025-04-21T16:31:54.114+0800] {processor.py:186} INFO - Started process (PID=19359) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:31:54.116+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:31:54.117+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:31:54.117+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:31:54.135+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:31:54.132+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:31:54.135+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:31:54.135+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:31:54.135+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:31:54.176+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2025-04-21T16:34:42.218+0800] {processor.py:186} INFO - Started process (PID=19695) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:34:42.221+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:34:42.222+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:34:42.221+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:34:42.240+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:34:42.237+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:34:42.240+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:34:42.240+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:34:42.240+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:34:42.281+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2025-04-21T16:37:33.759+0800] {processor.py:186} INFO - Started process (PID=19992) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:37:33.761+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:37:33.761+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:37:33.761+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:37:33.778+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:37:33.775+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:37:33.778+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:37:33.778+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:37:33.779+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:37:33.816+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2025-04-21T16:40:23.582+0800] {processor.py:186} INFO - Started process (PID=20342) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:40:23.584+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:40:23.585+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:40:23.585+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:40:23.602+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:40:23.599+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:40:23.602+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:40:23.602+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:40:23.602+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:40:23.639+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2025-04-21T16:43:15.591+0800] {processor.py:186} INFO - Started process (PID=20619) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:43:15.594+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:43:15.594+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:43:15.594+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:43:15.609+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:43:15.607+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:43:15.609+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:43:15.609+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:43:15.610+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:43:15.645+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2025-04-21T16:46:07.597+0800] {processor.py:186} INFO - Started process (PID=20975) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:46:07.600+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:46:07.601+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:46:07.601+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:46:07.620+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:46:07.616+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:46:07.620+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:46:07.620+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:46:07.620+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:46:07.661+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2025-04-21T16:48:59.822+0800] {processor.py:186} INFO - Started process (PID=21372) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:48:59.824+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:48:59.824+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:48:59.824+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:48:59.842+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:48:59.839+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:48:59.842+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:48:59.842+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:48:59.842+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:48:59.880+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2025-04-21T16:51:48.217+0800] {processor.py:186} INFO - Started process (PID=21710) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:51:48.220+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:51:48.220+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:51:48.220+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:51:48.236+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:51:48.234+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:51:48.236+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:51:48.236+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:51:48.236+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:51:48.273+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2025-04-21T16:54:44.456+0800] {processor.py:186} INFO - Started process (PID=22029) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:54:44.458+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:54:44.459+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:54:44.459+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:54:44.476+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:54:44.473+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:54:44.476+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:54:44.476+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:54:44.476+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:54:44.518+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2025-04-21T16:57:33.393+0800] {processor.py:186} INFO - Started process (PID=22342) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:57:33.395+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T16:57:33.395+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:57:33.395+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:57:33.413+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:57:33.410+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T16:57:33.413+0800] {logging_mixin.py:190} INFO - [2025-04-21T16:57:33.413+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T16:57:33.413+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T16:57:33.452+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2025-04-21T17:02:41.238+0800] {processor.py:186} INFO - Started process (PID=22939) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T17:02:41.240+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T17:02:41.240+0800] {logging_mixin.py:190} INFO - [2025-04-21T17:02:41.240+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T17:02:41.258+0800] {logging_mixin.py:190} INFO - [2025-04-21T17:02:41.255+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T17:02:41.258+0800] {logging_mixin.py:190} INFO - [2025-04-21T17:02:41.258+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T17:02:41.258+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T17:02:41.295+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2025-04-21T17:04:35.147+0800] {processor.py:186} INFO - Started process (PID=23146) to work on /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T17:04:35.150+0800] {processor.py:914} INFO - Processing file /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-21T17:04:35.150+0800] {logging_mixin.py:190} INFO - [2025-04-21T17:04:35.150+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T17:04:35.165+0800] {logging_mixin.py:190} INFO - [2025-04-21T17:04:35.163+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-21T17:04:35.165+0800] {logging_mixin.py:190} INFO - [2025-04-21T17:04:35.165+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-21T17:04:35.165+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-21T17:04:35.201+0800] {processor.py:208} INFO - Processing /Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.055 seconds
